version: "3.3"
services:
  nginx:
    image: nginx:1.15
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ..:/var/www/app:cached
    depends_on:
      - php

  php:
    build: php
    volumes:
      - ..:/var/www/app:cached
    ports:
      - 8080:8080
    command: ./run.sh
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: 'serverName=${PHP_IDE_CONFIG__SERVER_NAME}'

  db:
    image: mysql:8
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - ${MYSQL_PORT}:3306

